version: '3.8'
services:
  learning_db:
    image: postgres:latest
    container_name: postgres_dev
    restart: always
    env_file: 
      - .env
    volumes:
      - dev_data:/var/lib/postgresql/data
      - ./postgres-dev.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5430:5432"
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    networks:
      learning_net:
        ipv4_address: 172.21.0.2

volumes:
  dev_data:

networks:
  learning_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16