version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_dev
    env_file: 
      - .env
    volumes:
      - dev_data:/var/lib/postgresql/data
      - ./postgres-dev.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5430:5432"
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf

volumes:
  dev_data:
