version: '3.8'

services:
  database:
    image: postgres:16.2
    environment: 
      - ENVIROMENT=$ENVIRONMENT
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--data-checksums
    container_name: database
    restart: always
    volumes:
      - ./database/postgres-$ENVIRONMENT.conf:/etc/postgresql/postgresql.conf
      - ./database/source_data:/source_data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
