version: '3.8'

services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ./database/postgres-$ENVIRONMENT.conf:/etc/postgresql/postgresql.conf
    env_file: 
      - database/database.env
    container_name: postgres
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      db_network:
        aliases:
          - database

  # mlflow:
  #   image: ghcr.io/mlflow/mlflow
  #   command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env
  #   networks:
  #     - mlflow_network
  #     - db_network

networks:
  db_network:
    driver: bridge
  mlflow_network:
    driver: bridge
