[tool.poetry]
name = "master-proj"
version = "1.0.2"
description = "code associated w ms stats capstone"
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
baycomp = "*"
seaborn = "^0.13"
scikit-posthocs = "*"
alexlib = {git = "http://github.com/witzbeck/alexlib.git", branch = "dev"}

[tool.poetry.group.test.dependencies]
sqlfluff = "^2.3"
pytest = "^8.0"
pytest-cov = "^4.1"
pytest-mock = "^3.12"
pytest-xdist = "^3.5"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29"
tqdm = "^4.66"

[tool.pytest.ini_options]
addopts = [
    "--cov=src", 
    "--cov-report=term-missing", 
    "--cov-fail-under=0", 
    "--cov-branch"
]
testpaths = ["tests"]

[tool.sqlfluff.core]
verbose = 0
dialect = "postgres"
sql_file_exts = ".sql"
max_line_length = 120
processes = 0
rules = "core"

[tool.sqlfluff.layout.type.comma]
line_position = "leading"
spacing_before = "touch"

[tool.sqlfluff.indentation]
indent_unit = "space"
indented_then = false
indented_joins = true
trailing_comments = "after"

[tool.sqlfluff.layout.type.alias_expression]
spacing_before = "align"
align_scope = "file"

[tool.sqlfluff.capitalisation]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.aliasing.table]
aliasing = "implicit"

[tool.sqlfluff.rules.aliasing.column]
aliasing = "implicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
