[tool.poetry]
name = "master-proj"
version = "1.0.0"
description = "code associated w ms stats capstone"
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
scikit-learn = "*"
tqdm = "*"
baycomp = "*"
seaborn = "*"
scikit-posthocs = "*"
alexlib = {path = "../alexlib"}
psycopg-binary = "^3.1.16"

[tool.poetry.group.dev.dependencies]
alexlib = {path = "../alexlib", develop = true}
pytest = "*"
coverage = "*"
ipykernel = "*"

[tool.sqlfluff]
dialect = "postgres"
max_line_length = 120

[tool.sqlfluff.capitalization]
capitalization_policy = "lower"

[tool.sqlfluff.indentation]
indent_unit = "space"
use_vertical_hanging_indent = "True"
allow_implicit_indents = "True"

[tool.sqlfluff.layout.type.commas]
line_position = "leading"

[tool.sqlfluff.layout.type.alias_expression]
spacing_before = "align"
align_scope = "file"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
