[tool.poetry]
name = "master-proj"
version = "1.0.0"
description = "code associated w ms stats capstone"
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
scikit-learn = "*"
tqdm = "*"
baycomp = "*"
seaborn = "*"
scikit-posthocs = "*"
alexlib = {path = "../alexlib"}

[tool.poetry.group.dev.dependencies]
alexlib = {path = "../alexlib", develop = true}
pytest = "*"
coverage = "*"
ipykernel = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
