[tool.poetry]
name = "master-proj"
version = "1.1.0"
description = "code and docs from master's project"
authors = ["Alex Beckwith <57322567+witzbeck@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "master_proj"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.3"
scipy = "^1.11.1"
scikit-learn = "^1.3.0"
tqdm = "^4.65.0"
psycopg2 = "^2.9.6"
matplotlib = "^3.7.2"
baycomp = "^1.0.3"
seaborn = "^0.12.2"
scikit-posthocs = "^0.7.0"
dotenv = "^0.0.5"
SQLAlchemy = "^2.0.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
