from packages.core import QUERY_PATH

from .analysis import CREATE_ANALYSIS_ABROCA_TABLE
from .model import (
    CREATE_MODEL_FEATURES_TABLE,
    CREATE_MODEL_RESULTS_TABLE,
    CREATE_MODEL_RUNS_TABLE,
    CREATE_MODEL_TYPES_TABLE,
    CREATE_MODEL_WARNINGS_TABLE,
)

SCHEMAS = {x.name.split("_")[-1] for x in QUERY_PATH.iterdir() if x.is_dir()}
CREATE_TABLES = (
    CREATE_MODEL_RUNS_TABLE,
    CREATE_MODEL_TYPES_TABLE,
    CREATE_MODEL_RESULTS_TABLE,
    CREATE_MODEL_FEATURES_TABLE,
    CREATE_MODEL_WARNINGS_TABLE,
    CREATE_ANALYSIS_ABROCA_TABLE,
)
SOURCE_TABLES = {
    "MODEL_RUNS",
    "MODEL_TYPES",
    "MODEL_RESULTS",
    "LANDING_ASSESSMENTS",
    "LANDING_COURSES",
    "LANDING_STUDENT_ASSESSMENT",
    "LANDING_STUDENT_INFO",
    "LANDING_STUDENT_REGISTRATION",
    "LANDING_STUDENT_VLE",
    "LANDING_VLE",
}
