select r.student_id,
    r.n_max_revists,
    r.n_min_revists,
    r.n_sum_top_5_revists,
    r.avg_top_5_revists,
    r.n_top_days,
    a.n_times_accessed_dataplus,
    a.n_times_accessed_dualpane,
    a.n_times_accessed_externalquiz,
    a.n_times_accessed_folder,
    a.n_times_accessed_forumng,
    a.n_times_accessed_glossary,
    a.n_times_accessed_homepage,
    a.n_times_accessed_htmlactivity,
    a.n_times_accessed_oucollaborate,
    a.n_times_accessed_oucontent,
    a.n_times_accessed_ouelluminate,
    a.n_times_accessed_ouwiki,
    a.n_times_accessed_page,
    a.n_times_accessed_questionnaire,
    a.n_times_accessed_quiz,
    a.n_times_accessed_repeatactivity,
    a.n_times_accessed_resource,
    a.n_times_accessed_sharedsubpage,
    a.n_times_accessed_subpage,
    a.n_times_accessed_url
from agg.student_activity_revists r
    join agg.interactions_times_accessed_activity a on a.student_id = r.student_id