version: '3.8'
services:
  learning_db:
    image: postgres:latest
    container_name: postgres_prod
    restart: always
    env_file: 
      - .env
    volumes:
      - prod_data:/var/lib/postgresql/data
      - ./postgres-prod.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    networks:
      learning_net:
        ipv4_address: 172.23.0.4

volumes:
  prod_data:

networks:
  learning_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16