name: CI Pipeline

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    outputs:
      etl_hash: ${{ steps.etl-hash.outputs.hash }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Calculate ETL Hash
        id: etl-hash
        shell: bash
        run: |
          ETL_HASH=$(find etl data_sources -type f -exec sha256sum {} \; | sha256sum)
          echo "hash=${ETL_HASH}" >> $GITHUB_OUTPUT

  cache-etl-output:
    runs-on: ubuntu-latest
    needs: check-dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore ETL Cache
        id: etl-cache
        uses: actions/cache@v3
        with:
          path: path/to/etl/output
          key: etl-output-${{ needs.check-dependencies.outputs.etl_hash }}

      - name: Run ETL
        if: steps.etl-cache.outputs.cache-hit != 'true'
        run: poetry run pipe-etl

      - name: Save ETL Output to Cache
        if: steps.etl-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: path/to/etl/output
          key: etl-output-${{ needs.check-dependencies.outputs.etl_hash }}

  analysis:
    runs-on: ubuntu-latest
    needs: cache-etl-output
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore ETL Output
        uses: actions/cache@v3
        with:
          path: path/to/etl/output
          key: etl-output-${{ needs.check-dependencies.outputs.etl_hash }}

      - name: Run Analysis
        run: poetry run start-analysis

      - name: Upload Analysis Results
        uses: actions/upload-artifact@v3
        with:
          name: analysis-results
          path: ./output
