name: Master's Project | Build & Test Python

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-build.yaml'
      - 'database/**'
      - 'docker-compose.yaml'
      - '**/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-build.yaml'
      - 'database/**'
      - 'docker-compose.yaml'
      - '**/Dockerfile'

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: witzbeck/learning-analytics-database:latest