name: Ruff Check

on: [pull_request]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: astral-sh/ruff-action@v1
        with:
          changed-files: true
