name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "src/packages/etl/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Files to Docker Context
        run: |
          cp -r src/packages ./src/packages/etl/src/
          cp -r src/queries ./src/packages/etl/src/

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/packages/etl
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository }}:latest
