name: Master's Project | Build & Test Python

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/python-build.yaml'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/python-build.yaml'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        python-version: ['3.13', '3.12', '3.11']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Load Cached Virtualenv
      id: load-cached-virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Get Dataset
      run: uv run get-data

    - name: Run Tests
      run: uv run pytest
